In [1]:
import pandas as pd
import numpy as np
import re
import urllib.request
from datetime import date

In [2]:
data = pd.read_html('https://us-central1-dopami.cloudfunctions.net/exportAdgemData')
data

[                                        0                             1  \
 0                          transaction_id                           uid
 1    00cb94c5-2ca3-4760-a515-f5cca9361d44  63f4yk9j3abmIUFi0IWgJvXd2X23
 2    01ca3643-c08e-4790-a570-dac43434ba96  ytRdwKomKhgdLFp896mcUYVLvQg1
 3    026392bb-6522-4000-85ac-33d8e1129fb0  cWhUouRv8JZKxGqCinCY1Zjj3li1
 4    0281afd2-f1d0-4b97-9ced-c2eede01ac4e  AEepk3qHZJXeM4hAaWVrBLBKV3r1
 ..                                    ...                           ...
 559  fdcc109e-330a-4ab1-a989-475e2d1d7fef  wa9sFZZ3hrMswSD5IGaah9nYCUJ3
 560  fe165a7d-a55d-4865-937c-e2549fd34872  cWhUouRv8JZKxGqCinCY1Zjj3li1
 561  fefdc9fe-5a29-4976-94d0-833dfcbbdd8c  g9TA3KM0PxfBpapWLHY6OWby7jv2
 562  ff895b33-deb1-4d3a-ab6a-cac73a02e9cc  io3hoAYaklWJcwxTC18OiyyICn12
 563  ffcb0ed5-3f31-4f4e-aaf4-12bfcf47f988  K3N4sQd4foTIw0Qx9GFKX30sZQw2

           2                                                  3  \
 0    amount                                     click_datetime
 1      2486  Sat Sep 17 2022 17:15:47 GMT+0000 (Coordinated...
 2      2442  Sun Sep 18 2022 10:44:21 GMT+0000 (Coordinated...
 3      4884  Tue Oct 11 2022 12:11:00 GMT+0000 (Coordinated...
 4       666  Sat Nov 26 2022 20:03:41 GMT+0000 (Coordinated...
 ..      ...                                                ...
 559    1598  Fri Sep 02 2022 00:52:30 GMT+0000 (Coordinated...
 560    3552  Wed Oct 12 2022 09:52:50 GMT+0000 (Coordinated...
 561    2220  Sun Oct 09 2022 04:48:51 GMT+0000 (Coordinated...
 562   0.215  Sat Dec 03 2022 10:59:53 GMT+0000 (Coordinated...
 563     666  Fri Oct 21 2022 22:59:20 GMT+0000 (Coordinated...

                                                      4  \
 0                                  conversion_datetime
 1    Sat Sep 17 2022 17:18:09 GMT+0000 (Coordinated...
 2    Thu Sep 22 2022 03:09:30 GMT+0000 (Coordinated...
 3    Wed Oct 12 2022 01:40:33 GMT+0000 (Coordinated...
 4    Mon Nov 28 2022 11:14:51 GMT+0000 (Coordinated...
 ..                                                 ...
 559  Sat Sep 03 2022 03:01:48 GMT+0000 (Coordinated...
 560  Wed Oct 12 2022 10:22:49 GMT+0000 (Coordinated...
 561  Wed Oct 12 2022 10:47:28 GMT+0000 (Coordinated...
 562  Sat Dec 03 2022 11:31:29 GMT+0000 (Coordinated...
 563  Tue Oct 25 2022 02:01:28 GMT+0000 (Coordinated...

                                                      5            6  \
 0                                        campaign_name  campaign_id
 1             Shopee - (Android, INCENT, Free, ID, 5M)        17579
 2                  FID_PL_ES_CZ_PH_ID_BR_PT_LVL100_And        15706
 3                   SB_PL_ES_CZ_PH_ID_BR_PT_LVL250_And        17161
 4    They Are Coming - CPE - Level 10 (Android, INC...        17318
 ..                                                 ...          ...
 559             ccs_asia_android_ron_all_cpe_ptest_all        16258
 560               BT2_BR_PT_ES_PL_ID_SA_LVL200_Android        12883
 561  Color Water Sort - CPE: Level 100 (Android, IN...        16590
 562                                    BitLabs Surveys        18128
 563  AdAction - Slottist AND - WW Tier 3 - CPE - Mu...        18249

                 7             8
 0            city        device
 1         Jakarta       CPH2239
 2        Surabaya    M2003J15SC
 3      Yogyakarta  Redmi Note 8
 4           Batam      SM-A325F
 ..            ...           ...
 559       Jakarta       RMX2163
 560    Yogyakarta  Redmi Note 8
 561        Sleman       CPH2113
 562       Jakarta       CPH1901
 563  Kebumen Satu       CPH1911

 [564 rows x 9 columns]]

In [3]:
data = data[0]
data.columns = data.iloc[0]
data = data.drop(data.index[0])
data

,transaction_id,uid,amount,click_datetime,conversion_datetime,campaign_name,campaign_id,city,device
1,00cb94c5-2ca3-4760-a515-f5cca9361d44,63f4yk9j3abmIUFi0IWgJvXd2X23,2486,Sat Sep 17 2022 17:15:47 GMT+0000 (Coordinated...,Sat Sep 17 2022 17:18:09 GMT+0000 (Coordinated...,"Shopee - (Android, INCENT, Free, ID, 5M)",17579,Jakarta,CPH2239
2,01ca3643-c08e-4790-a570-dac43434ba96,ytRdwKomKhgdLFp896mcUYVLvQg1,2442,Sun Sep 18 2022 10:44:21 GMT+0000 (Coordinated...,Thu Sep 22 2022 03:09:30 GMT+0000 (Coordinated...,FID_PL_ES_CZ_PH_ID_BR_PT_LVL100_And,15706,Surabaya,M2003J15SC
3,026392bb-6522-4000-85ac-33d8e1129fb0,cWhUouRv8JZKxGqCinCY1Zjj3li1,4884,Tue Oct 11 2022 12:11:00 GMT+0000 (Coordinated...,Wed Oct 12 2022 01:40:33 GMT+0000 (Coordinated...,SB_PL_ES_CZ_PH_ID_BR_PT_LVL250_And,17161,Yogyakarta,Redmi Note 8
4,0281afd2-f1d0-4b97-9ced-c2eede01ac4e,AEepk3qHZJXeM4hAaWVrBLBKV3r1,666,Sat Nov 26 2022 20:03:41 GMT+0000 (Coordinated...,Mon Nov 28 2022 11:14:51 GMT+0000 (Coordinated...,"They Are Coming - CPE - Level 10 (Android, INC...",17318,Batam,SM-A325F
5,02aa6db6-0ad2-421a-90f6-99bba6f76687,TakzBMDFdleAZyepEupG0F7qm273,444,Fri Sep 09 2022 03:47:37 GMT+0000 (Coordinated...,Fri Sep 09 2022 03:51:51 GMT+0000 (Coordinated...,"Castle Clash - (Android, Free, INCENT, ROW, 30...",4978,Jakarta,CPH2333
...,...,...,...,...,...,...,...,...,...
559,fdcc109e-330a-4ab1-a989-475e2d1d7fef,wa9sFZZ3hrMswSD5IGaah9nYCUJ3,1598,Fri Sep 02 2022 00:52:30 GMT+0000 (Coordinated...,Sat Sep 03 2022 03:01:48 GMT+0000 (Coordinated...,ccs_asia_android_ron_all_cpe_ptest_all,16258,Jakarta,RMX2163
560,fe165a7d-a55d-4865-937c-e2549fd34872,cWhUouRv8JZKxGqCinCY1Zjj3li1,3552,Wed Oct 12 2022 09:52:50 GMT+0000 (Coordinated...,Wed Oct 12 2022 10:22:49 GMT+0000 (Coordinated...,BT2_BR_PT_ES_PL_ID_SA_LVL200_Android,12883,Yogyakarta,Redmi Note 8
561,fefdc9fe-5a29-4976-94d0-833dfcbbdd8c,g9TA3KM0PxfBpapWLHY6OWby7jv2,2220,Sun Oct 09 2022 04:48:51 GMT+0000 (Coordinated...,Wed Oct 12 2022 10:47:28 GMT+0000 (Coordinated...,"Color Water Sort - CPE: Level 100 (Android, IN...",16590,Sleman,CPH2113
562,ff895b33-deb1-4d3a-ab6a-cac73a02e9cc,io3hoAYaklWJcwxTC18OiyyICn12,0.215,Sat Dec 03 2022 10:59:53 GMT+0000 (Coordinated...,Sat Dec 03 2022 11:31:29 GMT+0000 (Coordinated...,BitLabs Surveys,18128,Jakarta,CPH1901
563,ffcb0ed5-3f31-4f4e-aaf4-12bfcf47f988,K3N4sQd4foTIw0Qx9GFKX30sZQw2,666,Fri Oct 21 2022 22:59:20 GMT+0000 (Coordinated...,Tue Oct 25 2022 02:01:28 GMT+0000 (Coordinated...,AdAction - Slottist AND - WW Tier 3 - CPE - Mu...,18249,Kebumen Satu,CPH1911

In [4]:
data['conversion_datetime'] = data['conversion_datetime'].str.replace(r'\d+\:\d+\:\d+\s\w+\+\d+\s\(\w+\s\w+\s\w+\)','')
data['conversion_datetime'] = data['conversion_datetime'].str.replace(r'^\w+','')
data

/tmp/ipykernel_10410/3056171332.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data['conversion_datetime'] = data['conversion_datetime'].str.replace(r'\d+\:\d+\:\d+\s\w+\+\d+\s\(\w+\s\w+\s\w+\)','')
/tmp/ipykernel_10410/3056171332.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  data['conversion_datetime'] = data['conversion_datetime'].str.replace(r'^\w+','')

,transaction_id,uid,amount,click_datetime,conversion_datetime,campaign_name,campaign_id,city,device
1,00cb94c5-2ca3-4760-a515-f5cca9361d44,63f4yk9j3abmIUFi0IWgJvXd2X23,2486,Sat Sep 17 2022 17:15:47 GMT+0000 (Coordinated...,Sep 17 2022,"Shopee - (Android, INCENT, Free, ID, 5M)",17579,Jakarta,CPH2239
2,01ca3643-c08e-4790-a570-dac43434ba96,ytRdwKomKhgdLFp896mcUYVLvQg1,2442,Sun Sep 18 2022 10:44:21 GMT+0000 (Coordinated...,Sep 22 2022,FID_PL_ES_CZ_PH_ID_BR_PT_LVL100_And,15706,Surabaya,M2003J15SC
3,026392bb-6522-4000-85ac-33d8e1129fb0,cWhUouRv8JZKxGqCinCY1Zjj3li1,4884,Tue Oct 11 2022 12:11:00 GMT+0000 (Coordinated...,Oct 12 2022,SB_PL_ES_CZ_PH_ID_BR_PT_LVL250_And,17161,Yogyakarta,Redmi Note 8
4,0281afd2-f1d0-4b97-9ced-c2eede01ac4e,AEepk3qHZJXeM4hAaWVrBLBKV3r1,666,Sat Nov 26 2022 20:03:41 GMT+0000 (Coordinated...,Nov 28 2022,"They Are Coming - CPE - Level 10 (Android, INC...",17318,Batam,SM-A325F
5,02aa6db6-0ad2-421a-90f6-99bba6f76687,TakzBMDFdleAZyepEupG0F7qm273,444,Fri Sep 09 2022 03:47:37 GMT+0000 (Coordinated...,Sep 09 2022,"Castle Clash - (Android, Free, INCENT, ROW, 30...",4978,Jakarta,CPH2333
...,...,...,...,...,...,...,...,...,...
559,fdcc109e-330a-4ab1-a989-475e2d1d7fef,wa9sFZZ3hrMswSD5IGaah9nYCUJ3,1598,Fri Sep 02 2022 00:52:30 GMT+0000 (Coordinated...,Sep 03 2022,ccs_asia_android_ron_all_cpe_ptest_all,16258,Jakarta,RMX2163
560,fe165a7d-a55d-4865-937c-e2549fd34872,cWhUouRv8JZKxGqCinCY1Zjj3li1,3552,Wed Oct 12 2022 09:52:50 GMT+0000 (Coordinated...,Oct 12 2022,BT2_BR_PT_ES_PL_ID_SA_LVL200_Android,12883,Yogyakarta,Redmi Note 8
561,fefdc9fe-5a29-4976-94d0-833dfcbbdd8c,g9TA3KM0PxfBpapWLHY6OWby7jv2,2220,Sun Oct 09 2022 04:48:51 GMT+0000 (Coordinated...,Oct 12 2022,"Color Water Sort - CPE: Level 100 (Android, IN...",16590,Sleman,CPH2113
562,ff895b33-deb1-4d3a-ab6a-cac73a02e9cc,io3hoAYaklWJcwxTC18OiyyICn12,0.215,Sat Dec 03 2022 10:59:53 GMT+0000 (Coordinated...,Dec 03 2022,BitLabs Surveys,18128,Jakarta,CPH1901
563,ffcb0ed5-3f31-4f4e-aaf4-12bfcf47f988,K3N4sQd4foTIw0Qx9GFKX30sZQw2,666,Fri Oct 21 2022 22:59:20 GMT+0000 (Coordinated...,Oct 25 2022,AdAction - Slottist AND - WW Tier 3 - CPE - Mu...,18249,Kebumen Satu,CPH1911

In [5]:
today = date.today()
day = today.strftime("%b-%d-%Y").replace('-', ' ')
day
# day = 'Sep 17 2022'

'Jan 22 2023'

In [6]:
data_time_1 = data['conversion_datetime']
data_time_1

1       Sep 17 2022
2       Sep 22 2022
3       Oct 12 2022
4       Nov 28 2022
5       Sep 09 2022
           ...
559     Sep 03 2022
560     Oct 12 2022
561     Oct 12 2022
562     Dec 03 2022
563     Oct 25 2022
Name: conversion_datetime, Length: 563, dtype: object

In [7]:
pat = r'\w+\s\w+\s\w+'

In [8]:
data_now = []
data_past = []
for i, time in enumerate(data_time_1):
    try:
        check_time = re.search(pat, time)
        check_now = re.search(pat, day)
    except KeyError:
        pass
    else:
        if check_time.group() == check_now.group():
            data_now.append(time)     
        else:
            data_past.append(time)

In [9]:
data_now

[]

In [10]:
data_past

[' Sep 17 2022 ',
 ' Sep 22 2022 ',
 ' Oct 12 2022 ',
 ' Nov 28 2022 ',
 ' Sep 09 2022 ',
 ' Oct 05 2022 ',
 ' Sep 28 2022 ',
 ' Oct 18 2022 ',
 ' Aug 26 2022 ',
 ' Sep 06 2022 ',
 ' Sep 02 2022 ',
 ' Sep 20 2022 ',
 ' Sep 15 2022 ',
 ' Dec 06 2022 ',
 ' Nov 23 2022 ',
 ' Sep 02 2022 ',
 ' Oct 19 2022 ',
 ' Oct 01 2022 ',
 ' Dec 04 2022 ',
 ' Sep 16 2022 ',
 ' Sep 17 2022 ',
 ' Sep 16 2022 ',
 ' Sep 19 2022 ',
 ' Oct 26 2022 ',
 ' Sep 17 2022 ',
 ' Sep 17 2022 ',
 ' Sep 04 2022 ',
 ' Sep 03 2022 ',
 ' Sep 17 2022 ',
 ' Sep 18 2022 ',
 ' Sep 17 2022 ',
 ' Sep 02 2022 ',
 ' Sep 17 2022 ',
 ' Oct 05 2022 ',
 ' Sep 13 2022 ',
 ' Sep 02 2022 ',
 ' Sep 15 2022 ',
 ' Jan 13 2023 ',
 ' Oct 27 2022 ',
 ' Sep 19 2022 ',
 ' Sep 17 2022 ',
 ' Sep 25 2022 ',
 ' Sep 15 2022 ',
 ' Oct 04 2022 ',
 ' Sep 07 2022 ',
 ' Dec 04 2022 ',
 ' Oct 02 2022 ',
 ' Dec 04 2022 ',
 ' Oct 05 2022 ',
 ' Sep 30 2022 ',
 ' Sep 19 2022 ',
 ' Oct 03 2022 ',
 ' Dec 20 2022 ',
 ' Oct 27 2022 ',
 ' Dec 10 2022 ',
 ' Sep 18 2022 ',
 ' Oct 10 2022 ',
 ' Sep 08 2022 ',
 ' Aug 28 2022 ',
 ' Aug 28 2022 ',
 ' Aug 28 2022 ',
 ' Jan 16 2023 ',
 ' Oct 06 2022 ',
 ' Oct 01 2022 ',
 ' Sep 15 2022 ',
 ' Oct 01 2022 ',
 ' Nov 17 2022 ',
 ' Sep 20 2022 ',
 ' Sep 04 2022 ',
 ' Sep 06 2022 ',
 ' Sep 12 2022 ',
 ' Sep 16 2022 ',
 ' Sep 17 2022 ',
 ' Aug 24 2022 ',
 ' Sep 15 2022 ',
 ' Sep 27 2022 ',
 ' Aug 18 2022 ',
 ' Oct 28 2022 ',
 ' Sep 17 2022 ',
 ' Sep 03 2022 ',
 ' Sep 11 2022 ',
 ' Aug 24 2022 ',
 ' Aug 27 2022 ',
 ' Sep 20 2022 ',
 ' Sep 18 2022 ',
 ' Nov 16 2022 ',
 ' Oct 01 2022 ',
 ' Nov 21 2022 ',
 ' Sep 17 2022 ',
 ' Sep 25 2022 ',
 ' Oct 02 2022 ',
 ' Sep 19 2022 ',
 ' Sep 17 2022 ',
 ' Oct 05 2022 ',
 ' Oct 09 2022 ',
 ' Sep 17 2022 ',
 ' Aug 26 2022 ',
 ' Jan 10 2023 ',
 ' Sep 18 2022 ',
 ' Sep 03 2022 ',
 ' Oct 12 2022 ',
 ' Sep 11 2022 ',
 ' Oct 16 2022 ',
 ' Sep 17 2022 ',
 ' Oct 04 2022 ',
 ' Sep 18 2022 ',
 ' Sep 17 2022 ',
 ' Sep 30 2022 ',
 ' Oct 13 2022 ',
 ' Nov 25 2022 ',
 ' Sep 05 2022 ',
 ' Sep 06 2022 ',
 ' Sep 16 2022 ',
 ' Sep 19 2022 ',
 ' Oct 10 2022 ',
 ' Sep 07 2022 ',
 ' Sep 01 2022 ',
 ' Sep 29 2022 ',
 ' Nov 10 2022 ',
 ' Nov 21 2022 ',
 ' Aug 20 2022 ',
 ' Oct 02 2022 ',
 ' Oct 05 2022 ',
 ' Sep 17 2022 ',
 ' Sep 16 2022 ',
 ' Nov 28 2022 ',
 ' Aug 23 2022 ',
 ' Aug 21 2022 ',
 ' Sep 17 2022 ',
 ' Sep 05 2022 ',
 ' Sep 15 2022 ',
 ' Sep 20 2022 ',
 ' Oct 03 2022 ',
 ' Sep 16 2022 ',
 ' Oct 13 2022 ',
 ' Sep 03 2022 ',
 ' Sep 18 2022 ',
 ' Sep 17 2022 ',
 ' Sep 13 2022 ',
 ' Sep 07 2022 ',
 ' Nov 01 2022 ',
 ' Sep 17 2022 ',
 ' Dec 14 2022 ',
 ' Oct 05 2022 ',
 ' Oct 01 2022 ',
 ' Dec 06 2022 ',
 ' Sep 26 2022 ',
 ' Sep 07 2022 ',
 ' Nov 21 2022 ',
 ' Sep 03 2022 ',
 ' Oct 12 2022 ',
 ' Aug 25 2022 ',
 ' Sep 06 2022 ',
 ' Sep 07 2022 ',
 ' Oct 04 2022 ',
 ' Oct 14 2022 ',
 ' Sep 19 2022 ',
 ' Dec 25 2022 ',
 ' Aug 18 2022 ',
 ' Nov 21 2022 ',
 ' Sep 15 2022 ',
 ' Sep 16 2022 ',
 ' Sep 18 2022 ',
 ' Oct 27 2022 ',
 ' Sep 05 2022 ',
 ' Oct 02 2022 ',
 ' Sep 06 2022 ',
 ' Sep 03 2022 ',
 ' Sep 12 2022 ',
 ' Sep 28 2022 ',
 ' Nov 16 2022 ',
 ' Sep 05 2022 ',
 ' Oct 28 2022 ',
 ' Oct 05 2022 ',
 ' Sep 08 2022 ',
 ' Oct 13 2022 ',
 ' Oct 01 2022 ',
 ' Oct 02 2022 ',
 ' Oct 06 2022 ',
 ' Sep 17 2022 ',
 ' Sep 02 2022 ',
 ' Nov 15 2022 ',
 ' Sep 13 2022 ',
 ' Jan 20 2023 ',
 ' Sep 28 2022 ',
 ' Sep 17 2022 ',
 ' Oct 24 2022 ',
 ' Aug 28 2022 ',
 ' Sep 17 2022 ',
 ' Sep 07 2022 ',
 ' Sep 17 2022 ',
 ' Sep 04 2022 ',
 ' Oct 04 2022 ',
 ' Sep 26 2022 ',
 ' Dec 10 2022 ',
 ' Sep 18 2022 ',
 ' Sep 17 2022 ',
 ' Aug 25 2022 ',
 ' Sep 18 2022 ',
 ' Oct 28 2022 ',
 ' Aug 28 2022 ',
 ' Nov 16 2022 ',
 ' Sep 07 2022 ',
 ' Oct 26 2022 ',
 ' Aug 27 2022 ',
 ' Sep 17 2022 ',
 ' Sep 11 2022 ',
 ' Aug 13 2022 ',
 ' Sep 05 2022 ',
 ' Sep 16 2022 ',
 ' Oct 01 2022 ',
 ' Sep 18 2022 ',
 ' Sep 09 2022 ',
 ' Nov 22 2022 ',
 ' Sep 17 2022 ',
 ' Aug 31 2022 ',
 ' Oct 03 2022 ',
 ' Aug 25 2022 ',
 ' Sep 17 2022 ',
 ' Sep 17 2022 ',
 ' Oct 24 2022 ',
 ' Nov 04 2022 ',
 ' Oct 05 2022 ',
 ' Oct 03 2022 ',
 ' Sep 30 2022 ',
 ' Sep 30 2022 ',
 ' Sep 30 2022 ',
 ' Aug 25 2022 ',
 ' Sep 04 2022 ',
 ' Dec 10 2022 ',
 ' Sep 29 2022 ',
 ' Aug 30 2022 ',
 ' Sep 20 2022 ',
 ' Oct 01 2022 ',
 ' Oct 13 2022 ',
 ' Sep 03 2022 ',
 ' Oct 31 2022 ',
 ' Sep 17 2022 ',
 ' Sep 18 2022 ',
 ' Oct 12 2022 ',
 ' Sep 19 2022 ',
 ' Sep 17 2022 ',
 ' Sep 15 2022 ',
 ' Aug 26 2022 ',
 ' Oct 01 2022 ',
 ' Oct 12 2022 ',
 ' Oct 15 2022 ',
 ' Sep 17 2022 ',
 ' Sep 22 2022 ',
 ' Oct 09 2022 ',
 ' Oct 12 2022 ',
 ' Sep 17 2022 ',
 ' Sep 16 2022 ',
 ' Dec 10 2022 ',
 ' Oct 14 2022 ',
 ' Sep 15 2022 ',
 ' Aug 16 2022 ',
 ' Sep 27 2022 ',
 ' Sep 04 2022 ',
 ' Nov 02 2022 ',
 ' Sep 17 2022 ',
 ' Oct 24 2022 ',
 ' Oct 01 2022 ',
 ' Oct 04 2022 ',
 ' Oct 20 2022 ',
 ' Oct 05 2022 ',
 ' Sep 17 2022 ',
 ' Oct 02 2022 ',
 ' Sep 19 2022 ',
 ' Sep 14 2022 ',
 ' Sep 29 2022 ',
 ' Sep 18 2022 ',
 ' Sep 10 2022 ',
 ' Oct 05 2022 ',
 ' Sep 15 2022 ',
 ' Sep 18 2022 ',
 ' Sep 18 2022 ',
 ' Oct 04 2022 ',
 ' Sep 17 2022 ',
 ' Sep 17 2022 ',
 ' Sep 21 2022 ',
 ' Sep 09 2022 ',
 ' Dec 29 2022 ',
 ' Aug 27 2022 ',
 ' Oct 17 2022 ',
 ' Sep 20 2022 ',
 ' Aug 31 2022 ',
 ' Dec 04 2022 ',
 ' Oct 27 2022 ',
 ' Sep 05 2022 ',
 ' Sep 13 2022 ',
 ' Sep 28 2022 ',
 ' Sep 17 2022 ',
 ' Oct 05 2022 ',
 ' Sep 18 2022 ',
 ' Oct 09 2022 ',
 ' Sep 01 2022 ',
 ' Oct 31 2022 ',
 ' Aug 31 2022 ',
 ' Oct 01 2022 ',
 ' Oct 01 2022 ',
 ' Aug 28 2022 ',
 ' Oct 21 2022 ',
 ' Sep 22 2022 ',
 ' Aug 31 2022 ',
 ' Nov 03 2022 ',
 ' Oct 14 2022 ',
 ' Sep 17 2022 ',
 ' Oct 05 2022 ',
 ' Oct 14 2022 ',
 ' Sep 02 2022 ',
 ' Sep 16 2022 ',
 ' Sep 18 2022 ',
 ' Sep 17 2022 ',
 ' Oct 15 2022 ',
 ' Sep 12 2022 ',
 ' Sep 26 2022 ',
 ' Oct 31 2022 ',
 ' Sep 30 2022 ',
 ' Sep 18 2022 ',
 ' Oct 08 2022 ',
 ' Sep 17 2022 ',
 ' Sep 28 2022 ',
 ' Oct 03 2022 ',
 ' Jan 05 2023 ',
 ' Sep 21 2022 ',
 ' Sep 21 2022 ',
 ' Oct 05 2022 ',
 ' Oct 01 2022 ',
 ' Oct 01 2022 ',
 ' Sep 11 2022 ',
 ' Oct 05 2022 ',
 ' Sep 29 2022 ',
 ' Sep 05 2022 ',
 ' Sep 17 2022 ',
 ' Sep 17 2022 ',
 ' Oct 15 2022 ',
 ' Sep 17 2022 ',
 ' Dec 26 2022 ',
 ' Sep 17 2022 ',
 ' Oct 04 2022 ',
 ' Sep 02 2022 ',
 ' Oct 01 2022 ',
 ' Sep 12 2022 ',
 ' Oct 10 2022 ',
 ' Sep 05 2022 ',
 ' Sep 17 2022 ',
 ' Sep 29 2022 ',
 ' Sep 28 2022 ',
 ' Oct 16 2022 ',
 ' Sep 03 2022 ',
 ' Dec 05 2022 ',
 ' Oct 17 2022 ',
 ' Oct 31 2022 ',
 ' Oct 14 2022 ',
 ' Oct 02 2022 ',
 ' Sep 27 2022 ',
 ' Nov 23 2022 ',
 ' Sep 17 2022 ',
 ' Sep 21 2022 ',
 ' Sep 17 2022 ',
 ' Sep 09 2022 ',
 ' Sep 17 2022 ',
 ' Sep 05 2022 ',
 ' Sep 03 2022 ',
 ' Jan 20 2023 ',
 ' Oct 16 2022 ',
 ' Dec 28 2022 ',
 ' Sep 15 2022 ',
 ' Sep 12 2022 ',
 ' Sep 17 2022 ',
 ' Sep 11 2022 ',
 ' Oct 14 2022 ',
 ' Oct 05 2022 ',
 ' Sep 30 2022 ',
 ' Nov 09 2022 ',
 ' Sep 28 2022 ',
 ' Oct 01 2022 ',
 ' Sep 06 2022 ',
 ' Dec 04 2022 ',
 ' Sep 02 2022 ',
 ' Sep 17 2022 ',
 ' Sep 26 2022 ',
 ' Nov 10 2022 ',
 ' Dec 10 2022 ',
 ' Dec 19 2022 ',
 ' Sep 16 2022 ',
 ' Oct 15 2022 ',
 ' Sep 16 2022 ',
 ' Sep 13 2022 ',
 ' Sep 20 2022 ',
 ' Sep 15 2022 ',
 ' Aug 28 2022 ',
 ' Sep 17 2022 ',
 ' Sep 17 2022 ',
 ' Oct 05 2022 ',
 ' Sep 19 2022 ',
 ' Sep 08 2022 ',
 ' Oct 16 2022 ',
 ' Aug 28 2022 ',
 ' Sep 13 2022 ',
 ' Oct 02 2022 ',
 ' Sep 30 2022 ',
 ' Oct 03 2022 ',
 ' Oct 31 2022 ',
 ' Oct 14 2022 ',
 ' Oct 05 2022 ',
 ' Oct 31 2022 ',
 ' Sep 16 2022 ',
 ' Nov 02 2022 ',
 ' Oct 01 2022 ',
 ' Aug 08 2022 ',
 ' Sep 04 2022 ',
 ' Nov 28 2022 ',
 ' Nov 25 2022 ',
 ' Aug 29 2022 ',
 ' Oct 15 2022 ',
 ' Oct 02 2022 ',
 ' Sep 19 2022 ',
 ' Sep 16 2022 ',
 ' Oct 01 2022 ',
 ' Sep 17 2022 ',
 ' Aug 21 2022 ',
 ' Sep 17 2022 ',
 ' Sep 18 2022 ',
 ' Sep 09 2022 ',
 ' Oct 16 2022 ',
 ' Sep 03 2022 ',
 ' Oct 05 2022 ',
 ' Oct 03 2022 ',
 ' Aug 28 2022 ',
 ' Nov 08 2022 ',
 ' Oct 01 2022 ',
 ' Oct 21 2022 ',
 ' Sep 09 2022 ',
 ' Sep 17 2022 ',
 ' Sep 17 2022 ',
 ' Oct 05 2022 ',
 ' Sep 11 2022 ',
 ' Sep 17 2022 ',
 ' Nov 21 2022 ',
 ' Sep 17 2022 ',
 ' Oct 16 2022 ',
 ' Oct 10 2022 ',
 ' Oct 05 2022 ',
 ' Sep 17 2022 ',
 ' Sep 27 2022 ',
 ' Oct 01 2022 ',
 ' Nov 22 2022 ',
 ' Sep 17 2022 ',
 ' Sep 18 2022 ',
 ' Oct 14 2022 ',
 ' Oct 02 2022 ',
 ' Sep 19 2022 ',
 ' Oct 15 2022 ',
 ' Dec 03 2022 ',
 ' Sep 06 2022 ',
 ' Oct 07 2022 ',
 ' Aug 31 2022 ',
 ' Oct 23 2022 ',
 ' Oct 17 2022 ',
 ' Oct 31 2022 ',
 ' Oct 15 2022 ',
 ' Sep 25 2022 ',
 ' Sep 22 2022 ',
 ' Dec 03 2022 ',
 ' Sep 30 2022 ',
 ' Dec 12 2022 ',
 ' Oct 01 2022 ',
 ' Sep 19 2022 ',
 ' Sep 17 2022 ',
 ' Sep 13 2022 ',
 ' Oct 12 2022 ',
 ' Sep 17 2022 ',
 ' Sep 17 2022 ',
 ' Jan 02 2023 ',
 ' Sep 26 2022 ',
 ' Aug 18 2022 ',
 ' Aug 13 2022 ',
 ' Sep 21 2022 ',
 ' Sep 02 2022 ',
 ' Nov 29 2022 ',
 ' Oct 01 2022 ',
 ' Nov 07 2022 ',
 ' Oct 02 2022 ',
 ' Oct 05 2022 ',
 ' Nov 08 2022 ',
 ' Sep 16 2022 ',
 ' Oct 06 2022 ',
 ' Oct 10 2022 ',
 ' Oct 30 2022 ',
 ' Sep 18 2022 ',
 ' Aug 13 2022 ',
 ' Nov 10 2022 ',
 ' Sep 17 2022 ',
 ' Dec 14 2022 ',
 ' Aug 30 2022 ',
 ' Dec 17 2022 ',
 ' Aug 22 2022 ',
 ' Sep 14 2022 ',
 ' Sep 18 2022 ',
 ' Sep 03 2022 ',
 ' Oct 10 2022 ',
 ' Dec 03 2022 ',
 ' Sep 17 2022 ',
 ' Oct 08 2022 ',
 ' Sep 13 2022 ',
 ' Nov 17 2022 ',
 ' Oct 05 2022 ',
 ' Sep 28 2022 ',
 ' Oct 03 2022 ',
 ' Oct 13 2022 ',
 ' Aug 23 2022 ',
 ' Sep 29 2022 ',
 ' Sep 02 2022 ',
 ' Oct 05 2022 ',
 ' Nov 14 2022 ',
 ' Oct 04 2022 ',
 ' Nov 10 2022 ',
 ' Aug 31 2022 ',
 ' Sep 17 2022 ',
 ' Sep 23 2022 ',
 ' Oct 05 2022 ',
 ' Sep 05 2022 ',
 ' Sep 16 2022 ',
 ' Sep 10 2022 ',
 ' Sep 26 2022 ',
 ' Sep 17 2022 ',
 ' Sep 12 2022 ',
 ' Oct 05 2022 ',
 ' Sep 18 2022 ',
 ' Oct 12 2022 ',
 ' Oct 14 2022 ',
 ' Sep 26 2022 ',
 ' Sep 19 2022 ',
 ' Sep 21 2022 ',
 ' Oct 17 2022 ',
 ' Oct 15 2022 ',
 ' Oct 07 2022 ',
 ' Sep 16 2022 ',
 ' Sep 16 2022 ',
 ' Sep 13 2022 ',
 ' Aug 25 2022 ',
 ' Oct 28 2022 ',
 ' Oct 25 2022 ',
 ' Oct 14 2022 ',
 ' Sep 17 2022 ',
 ' Oct 05 2022 ',
 ' Sep 18 2022 ',
 ' Oct 16 2022 ',
 ' Aug 24 2022 ',
 ' Dec 05 2022 ',
 ' Sep 22 2022 ',
 ' Aug 30 2022 ',
 ' Sep 13 2022 ',
 ' Sep 17 2022 ',
 ' Sep 17 2022 ',
 ' Sep 17 2022 ',
 ' Sep 03 2022 ',
 ' Oct 12 2022 ',
 ' Oct 12 2022 ',
 ' Dec 03 2022 ',
 ' Oct 25 2022 ']

In [11]:
dataframe_now = data.loc[data['conversion_datetime'].isin(data_now)]
dataframe_now

Empty DataFrame
Columns: [transaction_id, uid, amount, click_datetime, conversion_datetime, campaign_name, campaign_id, city, device]
Index: []

In [12]:
dataframe_past = data.loc[data['conversion_datetime'].isin(data_past)]
dataframe_past

,transaction_id,uid,amount,click_datetime,conversion_datetime,campaign_name,campaign_id,city,device
1,00cb94c5-2ca3-4760-a515-f5cca9361d44,63f4yk9j3abmIUFi0IWgJvXd2X23,2486,Sat Sep 17 2022 17:15:47 GMT+0000 (Coordinated...,Sep 17 2022,"Shopee - (Android, INCENT, Free, ID, 5M)",17579,Jakarta,CPH2239
2,01ca3643-c08e-4790-a570-dac43434ba96,ytRdwKomKhgdLFp896mcUYVLvQg1,2442,Sun Sep 18 2022 10:44:21 GMT+0000 (Coordinated...,Sep 22 2022,FID_PL_ES_CZ_PH_ID_BR_PT_LVL100_And,15706,Surabaya,M2003J15SC
3,026392bb-6522-4000-85ac-33d8e1129fb0,cWhUouRv8JZKxGqCinCY1Zjj3li1,4884,Tue Oct 11 2022 12:11:00 GMT+0000 (Coordinated...,Oct 12 2022,SB_PL_ES_CZ_PH_ID_BR_PT_LVL250_And,17161,Yogyakarta,Redmi Note 8
4,0281afd2-f1d0-4b97-9ced-c2eede01ac4e,AEepk3qHZJXeM4hAaWVrBLBKV3r1,666,Sat Nov 26 2022 20:03:41 GMT+0000 (Coordinated...,Nov 28 2022,"They Are Coming - CPE - Level 10 (Android, INC...",17318,Batam,SM-A325F
5,02aa6db6-0ad2-421a-90f6-99bba6f76687,TakzBMDFdleAZyepEupG0F7qm273,444,Fri Sep 09 2022 03:47:37 GMT+0000 (Coordinated...,Sep 09 2022,"Castle Clash - (Android, Free, INCENT, ROW, 30...",4978,Jakarta,CPH2333
...,...,...,...,...,...,...,...,...,...
559,fdcc109e-330a-4ab1-a989-475e2d1d7fef,wa9sFZZ3hrMswSD5IGaah9nYCUJ3,1598,Fri Sep 02 2022 00:52:30 GMT+0000 (Coordinated...,Sep 03 2022,ccs_asia_android_ron_all_cpe_ptest_all,16258,Jakarta,RMX2163
560,fe165a7d-a55d-4865-937c-e2549fd34872,cWhUouRv8JZKxGqCinCY1Zjj3li1,3552,Wed Oct 12 2022 09:52:50 GMT+0000 (Coordinated...,Oct 12 2022,BT2_BR_PT_ES_PL_ID_SA_LVL200_Android,12883,Yogyakarta,Redmi Note 8
561,fefdc9fe-5a29-4976-94d0-833dfcbbdd8c,g9TA3KM0PxfBpapWLHY6OWby7jv2,2220,Sun Oct 09 2022 04:48:51 GMT+0000 (Coordinated...,Oct 12 2022,"Color Water Sort - CPE: Level 100 (Android, IN...",16590,Sleman,CPH2113
562,ff895b33-deb1-4d3a-ab6a-cac73a02e9cc,io3hoAYaklWJcwxTC18OiyyICn12,0.215,Sat Dec 03 2022 10:59:53 GMT+0000 (Coordinated...,Dec 03 2022,BitLabs Surveys,18128,Jakarta,CPH1901
563,ffcb0ed5-3f31-4f4e-aaf4-12bfcf47f988,K3N4sQd4foTIw0Qx9GFKX30sZQw2,666,Fri Oct 21 2022 22:59:20 GMT+0000 (Coordinated...,Oct 25 2022,AdAction - Slottist AND - WW Tier 3 - CPE - Mu...,18249,Kebumen Satu,CPH1911

In [13]:
dataframe_past_uid = dataframe_past['uid']
dataframe_past_uid

1      63f4yk9j3abmIUFi0IWgJvXd2X23
2      ytRdwKomKhgdLFp896mcUYVLvQg1
3      cWhUouRv8JZKxGqCinCY1Zjj3li1
4      AEepk3qHZJXeM4hAaWVrBLBKV3r1
5      TakzBMDFdleAZyepEupG0F7qm273
                   ...
559    wa9sFZZ3hrMswSD5IGaah9nYCUJ3
560    cWhUouRv8JZKxGqCinCY1Zjj3li1
561    g9TA3KM0PxfBpapWLHY6OWby7jv2
562    io3hoAYaklWJcwxTC18OiyyICn12
563    K3N4sQd4foTIw0Qx9GFKX30sZQw2
Name: uid, Length: 563, dtype: object

In [14]:
campaign_id_now = dataframe_now.groupby(['uid'])['campaign_id'].value_counts()
list_uid_fraud_now = list(campaign_id_now.where(campaign_id_now>1).dropna().index.get_level_values(0))
list_uid_fraud_now

[]

In [15]:
list_uid_fraud_now

[]

In [16]:
list_link = []
for uid_fraud_final in list_uid_fraud_now:
    list_link.append('https://us-central1-dopami.cloudfunctions.net/pointsCallback?uid='+uid_fraud_final+'&point=-50')
list_link

[]

In [17]:
for pengurangan_now in list_link:
    urllib.request.urlopen(pengurangan_now)